In [4]:
world={"China":1.38,"India":1.34,"USA":0.32}
print(type(world))
print(world.keys())
print(world.values())
print(world["India"])

<class 'dict'>
dict_keys(['China', 'India', 'USA'])
dict_values([1.38, 1.34, 0.32])
1.34


In [13]:
world["Indonesia"]=0.26
world["Brazil"]=0.21
print(world)
print("Indonesia" in world)
world["India"]=1.39
print(world)
del(world["Brazil"])
print(world)

{'China': 1.38, 'India': 1.39, 'USA': 0.32, 'Indonesia': 0.26, 'Brazil': 0.21}
True
{'China': 1.38, 'India': 1.39, 'USA': 0.32, 'Indonesia': 0.26, 'Brazil': 0.21}
{'China': 1.38, 'India': 1.39, 'USA': 0.32, 'Indonesia': 0.26}


In [16]:
world={"China":{'CAPITAL':'Beijing','Population':1.38},
       "India":{'CAPITAL':'New Delhi','Population':1.34},
       "USA":{'CAPITAL':'Washington D.C','Population':0.32}}

In [17]:
print(world)

{'China': {'CAPITAL': 'Beijing', 'Population': 1.38}, 'India': {'CAPITAL': 'New Delhi', 'Population': 1.34}, 'USA': {'CAPITAL': 'Washington D.C', 'Population': 0.32}}


In [19]:
print(world['India']['CAPITAL'])

New Delhi


In [23]:
data = {'CAPITAL':'Rome','Population':59.83}

In [24]:
world['italy']=data

In [25]:
print(world)

{'China': {'CAPITAL': 'Beijing', 'Population': 1.38}, 'India': {'CAPITAL': 'New Delhi', 'Population': 1.34}, 'USA': {'CAPITAL': 'Washington D.C', 'Population': 0.32}, 'italy': {'CAPITAL': 'Rome', 'Population': 59.83}}


In [27]:
world['Turkey'] = {'CAPITAL':'ANKARA','Population':49.83}
print(world)

{'China': {'CAPITAL': 'Beijing', 'Population': 1.38}, 'India': {'CAPITAL': 'New Delhi', 'Population': 1.34}, 'USA': {'CAPITAL': 'Washington D.C', 'Population': 0.32}, 'italy': {'CAPITAL': 'Rome', 'Population': 59.83}, 'Turkey': {'CAPITAL': 'ANKARA', 'Population': 49.83}}


In [29]:
Countries_names=['UNITED KINGDOM','AUSTRALIA','JAPAN','INDIA','RUSSIA','MOROCCO','EGYPT']
rightHandDriving=[True,False,False,False,True,True,True]
carAvg1000=[809,731,588,18,200,70,45]

In [30]:
import pandas as pd

In [35]:
myDict={'Coutries' : Countries_names,
        'driverRight' : rightHandDriving,
        'carAvgPer1000': carAvg1000
        
}

car = pd.DataFrame(myDict)
print(car)

         Coutries  driverRight  carAvgPer1000
0  UNITED KINGDOM         True            809
1       AUSTRALIA        False            731
2           JAPAN        False            588
3           INDIA        False             18
4          RUSSIA         True            200
5         MOROCCO         True             70
6           EGYPT         True             45


In [38]:
rowLabels=['US','AUS','JAP','IND','RU','MOR','EGP']
car.index=rowLabels
car

Coutries  driverRight  carAvgPer1000
US   UNITED KINGDOM         True            809
AUS       AUSTRALIA        False            731
JAP           JAPAN        False            588
IND           INDIA        False             18
RU           RUSSIA         True            200
MOR         MOROCCO         True             70
EGP           EGYPT         True             45

In [42]:
def raise_to_power(x,y):
    return x**y

raise_to_power(2,3)

8

In [41]:
#lambda
raise_to_power=lambda x,y: x**y
raise_to_power(2,3)

8

In [ ]:
def power(i):
    return i**2


In [44]:
#exception handelling

def sqrt(x):
    try:
        print(x**0.5)
    except:
        print('please enter number')
print('execute with inter value' )
sqrt(9)
print("execute with string value")
sqrt("abcd")
        

execute with inter value
3.0
execute with string value
please enter number


In [45]:
def sqrt(x):
    if x <0:
        raise ValueError("Entered value must in non negative")
    else:
        print(x**0.5)
        
print('execute with number')
print('execute with negative value')

execute with number
execute with negative value


In [2]:
nums=[3,6,4,10,1]
def more_than_5(x):
    y=[]
    for i in x:
        if i>5:
            y.append(i)
    return y
more_than_5(nums)

[6, 10]

In [3]:
# using lambda filter
nums=[3,6,4,10,1]
more_than_5 = filter(lambda num: num>5, nums)
list(more_than_5)

[6, 10]

In [7]:
primeNum = [2,3,5,7,11,13,17,19,23,29]

product = 1
for i in primeNum:
    product = product * i

In [9]:
#using reduce function
from functools import reduce

reduce(lambda x,y:x *y,primeNum)

6469693230

In [16]:
import numpy as np
a = np.arange(6)
b = np.arange(12).reshape(4,3)
c = np.arange(24).reshape(2,3,4)
d = np.arange(24).reshape(2,3,2,2)

print(a)
print("------")
print("------")
print(b)
print("------")
print("------")
print(c)
print("------")
print("------")
print(d)

[0 1 2 3 4 5]
------
------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
------
------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
------
------
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]


In [63]:
import numpy as np

a2dArray = np.array([[1.71,1.58,1.51,1.73,1.92],
                     [65.9,58.8,66.8,83.4,67.8]])
print(type(a2dArray))

print(a2dArray.shape)
#print(a2dArray[0])
print(a2dArray[0,:])
print(a2dArray[1,0:1])



<class 'numpy.ndarray'>
(2, 5)
[1.71 1.58 1.51 1.73 1.92]
[65.9]


In [69]:
print(np.random.randint(10,50,5))


[26 18 44 21 48]


In [77]:
np.random.seed(100)
print(np.random.randint(10,50,5))


[18 34 13 49 33]
